<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.7">
  <POU Name="RANGE_TO_BYTE" Id="{e5736efc-70e1-4436-a8eb-0439183653c8}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION RANGE_TO_BYTE : BYTE
VAR_INPUT
	X : REAL;
	low : REAL;
	high : REAL;
END_VAR


(*
version 1.0	9. jan 2008
programmer 	hugo
tested by		tobias

Range_to_byte converts a real value between low and high into a byte

*)]]></Declaration>
    <Implementation>
      <ST><![CDATA[RANGE_TO_BYTE := INT_TO_BYTE(TRUNC_INT((LIMIT(low, X, high) - low) * 255.0 / (high - low)));


(* revision history
hm	9. jan 2008		rev 1.0
	original version

*)
]]></ST>
    </Implementation>
    <LineIds Name="RANGE_TO_BYTE">
      <LineId Id="16" Count="8" />
    </LineIds>
  </POU>
</TcPlcObject>