<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.7">
  <POU Name="B_TRIG" Id="{627702fd-989d-4cb1-b3ad-379b4a7cb057}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK B_TRIG
VAR_INPUT
	CLK : BOOL;
END_VAR
VAR_OUTPUT
	Q : BOOL;
END_VAR
VAR
	edge : BOOL;
END_VAR

(*
version 1.0	4. aug. 2006
programmer 	hugo
tested by		tobias

this block is similar to R_trig and F_trig but it generates a pulse on rising and falling edge.

*)
]]></Declaration>
    <Implementation>
      <ST><![CDATA[Q := clk XOR edge;
edge := CLK;


(* revision history
hm		4. aug. 2006	rev 1.0
	original version

*)]]></ST>
    </Implementation>
    <LineIds Name="B_TRIG">
      <LineId Id="20" Count="8" />
    </LineIds>
  </POU>
</TcPlcObject>