<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.7">
  <POU Name="WORD_TO_RANGE" Id="{26c9a3f2-bfe2-408e-b836-69f82bfc5ec3}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION WORD_TO_RANGE : REAL
VAR_INPUT
	X : WORD;
	low : REAL;
	high : REAL;
END_VAR


(*
version 1.1	10. mar. 2009
programmer 	hugo
tested by		tobias

Word_to_Range converts a Byte into a real between low and high.

*)]]></Declaration>
    <Implementation>
      <ST><![CDATA[WORD_TO_RANGE := (high - low) * WORD_TO_REAL(X) * 0.00001525902189669640 + low;


(* revision history
hm	9. jan 2008	rev 1.0
	original version

hm	10. mar. 2009	rev 1.1
	improved code
*)
]]></ST>
    </Implementation>
    <LineIds Name="WORD_TO_RANGE">
      <LineId Id="16" Count="10" />
    </LineIds>
  </POU>
</TcPlcObject>