<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.7">
  <POU Name="TN_SC_SHADOW_ATTR" Id="{8b86c918-7ab2-451d-9520-049fde8d190c}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION TN_SC_SHADOW_ATTR : BYTE
VAR_INPUT
	Iby_ATTR : BYTE;
END_VAR

(*
version 1.0		10. mai 2010
programmer		ks
tested by		ks

TN_SC_SHADOW_ATTR berechnet aus einem normalen einem abgedunkelten Farbcode
*)
]]></Declaration>
    <Implementation>
      <ST><![CDATA[(* Background Farbe auf Schwarz ändern      *)
(* und dunkle Fordergrundfarben einschalten *)  
TN_SC_SHADOW_ATTR := ((Iby_ATTR AND BYTE#2#11110000) OR BYTE#2#00001000);

(* revision history
ks	10. mai. 2010	rev 1.0
	original version
*)]]></ST>
    </Implementation>
    <LineIds Name="TN_SC_SHADOW_ATTR">
      <LineId Id="13" Count="7" />
    </LineIds>
  </POU>
</TcPlcObject>