<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.7">
  <POU Name="REAL_TO_DW" Id="{626e883b-71cc-4fe6-971a-76928e4f2e0c}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION REAL_TO_DW : DWORD
VAR_INPUT
	X : REAL;
END_VAR
VAR
	pt : POINTER TO DWORD;
END_VAR

(*
version 1.0	18. apr. 2008
programmer 	hugo
tested by		tobias

this function converts a 32 Bit Real to a dword in a bitwise manner.
*)
]]></Declaration>
    <Implementation>
      <ST><![CDATA[pt := ADR(X);
REAL_TO_DW := pt^;

(* revision history
hm	18. apr. 2008
	original version

*)]]></ST>
    </Implementation>
    <LineIds Name="REAL_TO_DW">
      <LineId Id="16" Count="7" />
    </LineIds>
  </POU>
</TcPlcObject>