<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.7">
  <POU Name="SHR1" Id="{03153f11-7997-4d88-adeb-cadf845cd23e}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION SHR1 : DWORD
VAR_INPUT
	IN : DWORD;
	N : INT;
END_VAR
VAR CONSTANT
	temp : DWORD := 16#FFFF_FFFF;
END_VAR

(*
version 1.1	27 dec 2007
programmer 	hugo
tested by		tobias

SHR1 shifts N bits to the right filling the new bits with 1

*)]]></Declaration>
    <Implementation>
      <ST><![CDATA[SHR1 := SHL(temp,32-N) OR SHR(IN,N);

(* revision history
hm	14.9.2007		rev 1.0
	original version

hm	27. dec 2007	rev 1.1
	changed code for better performance

*)]]></ST>
    </Implementation>
    <LineIds Name="SHR1">
      <LineId Id="17" Count="9" />
    </LineIds>
  </POU>
</TcPlcObject>