<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.7">
  <POU Name="SWAP_BYTE" Id="{200fa275-d769-4079-ba0f-9b8171767570}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION SWAP_BYTE : WORD
VAR_INPUT
	IN : WORD;
END_VAR


(*
version 1.0	4 feb 2008
programmer 	hugo
tested by		tobias

This function swaps the high and low byte of the word in.

*)]]></Declaration>
    <Implementation>
      <ST><![CDATA[SWAP_BYTE := ROL(in,8);


(* revision history
hm		4. feb 2008	rev 1.0
	original version

*)]]></ST>
    </Implementation>
    <LineIds Name="SWAP_BYTE">
      <LineId Id="14" Count="7" />
    </LineIds>
  </POU>
</TcPlcObject>