<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.7">
  <POU Name="TN_SC_XY2_ERROR" Id="{ee13c8ba-4638-45fb-893c-c03ff2644fa4}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION TN_SC_XY2_ERROR : BOOL
VAR_INPUT
	X1 : INT;
	Y1 : INT;
	X2 : INT;
	Y2 : INT;
END_VAR

(*
version 1.0		10. mai 2010
programmer		ks
tested by		ks

TN_SC_XY2_ERROR prüft ob die angegenene Koordinaten die einen rechteckigen Bereich angeben gültig sind 
*)
]]></Declaration>
    <Implementation>
      <ST><![CDATA[(* min und max werte prüfen *)
TN_SC_XY2_ERROR := Y1 < 0 OR X1 < 0 OR Y2 < 0 OR X2 < 0 OR Y1 > 23 OR X1 > 79 OR Y2 > 23 OR X2 > 79;

(* revision history
ks	10. mai. 2010	rev 1.0
	original version
*)]]></ST>
    </Implementation>
    <LineIds Name="TN_SC_XY2_ERROR">
      <LineId Id="16" Count="6" />
    </LineIds>
  </POU>
</TcPlcObject>