<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.7">
  <POU Name="V3_PAR" Id="{f711b581-6baf-41fe-a753-05d7c6028d5c}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION V3_PAR : BOOL
VAR_INPUT
	A : Vector_3;
	B : Vector_3;
END_VAR


(*
version 1.1	10. mar. 2009
programmer 	hugo
tested by		tobias

this function checks if two vectors in a 3 dimensional space are parallel.
which means the two vectors have the same direction

*)]]></Declaration>
    <Implementation>
      <ST><![CDATA[V3_PAR := V3_ABS(V3_XPRO(A, B)) = 0.0;



(* revision history
hm	11 dec 2007	rev 1.0
	original version

hm	10. mar. 2009	rev 1.1
	changed syntax of real constants to 0.0

*)]]></ST>
    </Implementation>
    <LineIds Name="V3_PAR">
      <LineId Id="16" Count="11" />
    </LineIds>
  </POU>
</TcPlcObject>