<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.7">
  <POU Name="JD2000" Id="{c988a1ab-ad32-4dc2-b9da-5c5e7a0a779f}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION JD2000 : REAL
VAR_INPUT
	DTI : DT;
END_VAR


(*
version 1.0	15. jul. 2008
programmer 	hugo
tested by	oscat

JULIAN calculates the astronomic julian date from 1.1.2000-12:00.

*)]]></Declaration>
    <Implementation>
      <ST><![CDATA[JD2000 := DWORD_TO_REAL(DT_TO_DWORD(DTI) - 946728000) / 86400.0;

(* revision histroy
hm	15. jul. 2008	rev 1.0
	original release


*)	
]]></ST>
    </Implementation>
    <LineIds Name="JD2000">
      <LineId Id="14" Count="8" />
    </LineIds>
  </POU>
</TcPlcObject>