<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.7">
  <POU Name="CCOS" Id="{a5792ea0-5fb4-46c9-8425-179d4843cb5d}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION CCOS : complex
VAR_INPUT
	X : complex;
END_VAR


(*
version 1.0	21 feb 2008
programmer 	hugo
tested by		oscat

this function calculates the cosinus function of a complex number

*)]]></Declaration>
    <Implementation>
      <ST><![CDATA[CCOS := CCOSH(CSET(-X.im, X.re));


(* revision history
hm	21. feb 2008	rev 1.0
	original version

*)]]></ST>
    </Implementation>
    <LineIds Name="CCOS">
      <LineId Id="14" Count="7" />
    </LineIds>
  </POU>
</TcPlcObject>