<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.7">
  <POU Name="CLOG" Id="{e28eef0d-0653-4eeb-a074-a32d084619eb}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION CLOG : complex
VAR_INPUT
	X : complex;
END_VAR


(*
version 1.1	20. apr. 2008
programmer 	hugo
tested by	oscat

this function calculates the complex natural (base e) logarithm

*)]]></Declaration>
    <Implementation>
      <ST><![CDATA[CLOG.re := LN(HYPOT(X.re, X.im));
CLOG.im := ATAN2(X.im, X.re);


(* revision history
hm	21. feb 2008	rev 1.0
	original version

hm	20. apr. 2008	rev 1.1
	use ATAN2 instead of ATAN
*)]]></ST>
    </Implementation>
    <LineIds Name="CLOG">
      <LineId Id="14" Count="10" />
    </LineIds>
  </POU>
</TcPlcObject>