<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.7">
  <POU Name="SCALE" Id="{a2a256ea-53df-4538-bcd3-18f4b496bc9d}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION SCALE : REAL
VAR_INPUT
	X : REAL;
	K : REAL;
	O : REAL;
	MX : REAL;
	MN : REAL;
END_VAR


(*
version 1.0	16. may. 2008
programmer 	hugo
tested by		tobias

Scale is used to translate an input x to output by the formula Y = X*K + O.
at the same time the output is limited to MN and MX.

*)
]]></Declaration>
    <Implementation>
      <ST><![CDATA[SCALE := LIMIT(MN, X * K + O, MX);


(* revision history
hm	16. may. 2008		rev 1.0
	original version
*)]]></ST>
    </Implementation>
    <LineIds Name="SCALE">
      <LineId Id="20" Count="6" />
    </LineIds>
  </POU>
</TcPlcObject>