<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.7">
  <POU Name="ISC_NUM" Id="{012cb76e-d30a-4659-98c1-07efc6c131a9}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION ISC_NUM : BOOL
VAR_INPUT
	IN : BYTE;
END_VAR


(*
version 1.0	6. mar 2008
programmer 	oscat
tested by		hugo

ISC_NUM checks if a character is 0..9.

*)]]></Declaration>
    <Implementation>
      <ST><![CDATA[ISC_NUM := IN > 47 AND IN < 58;

(* revision history
hm		6. mar. 2008	rev 1.0
	original version

*)]]></ST>
    </Implementation>
    <LineIds Name="ISC_NUM">
      <LineId Id="14" Count="6" />
    </LineIds>
  </POU>
</TcPlcObject>