<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.7">
  <POU Name="ARRAY_SDV" Id="{eb538ff5-5459-4d2a-9eb4-938dbba94b5c}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION ARRAY_SDV : REAL
VAR_INPUT
	pt : POINTER TO ARRAY[0..32000] OF REAL;
	size : UINT;
END_VAR


(*
version 1.1	16. mar 2008
programmer 	hugo
tested by		tobias

this function will calculate the standard deviation of a given array.
the function needs to be called:	array_sdv(adr("array"),sizeof("array"));
because this function works with pointers its very time efficient and it needs no extra memory.

*)]]></Declaration>
    <Implementation>
      <ST><![CDATA[(* standard deviation is simply the square root of the variance *)

array_sdv := SQRT(array_var(pt, size));

(* revision history
hm 	1.4.2007		rev 1.0
	function created

hm	16. mar. 2008	rev 1.1
	changed type of input size to uint

*)]]></ST>
    </Implementation>
    <LineIds Name="ARRAY_SDV">
      <LineId Id="17" Count="11" />
    </LineIds>
  </POU>
</TcPlcObject>