<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.7">
  <POU Name="IP4_CHECK" Id="{d1621dac-7eac-42dd-bdf1-679dc03c4eb6}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION IP4_CHECK : BOOL
VAR_INPUT
	NIP : DWORD;
	LIP : DWORD;
	SM : DWORD;
END_VAR


(*
version 1.0	4. mar 2008
programmer 	hugo
tested by		oscat

IP4_CHECK testet ob eine Network IP und Local_IP im selben Subnet sind.

*)]]></Declaration>
    <Implementation>
      <ST><![CDATA[IP4_CHECK := (NIP AND sm) = (LIP AND SM);


(* revision history
hm		4. mar 2008	rev 1.0
	original version

*)]]></ST>
    </Implementation>
    <LineIds Name="IP4_CHECK">
      <LineId Id="16" Count="7" />
    </LineIds>
  </POU>
</TcPlcObject>