<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.7">
  <POU Name="F_LIN2" Id="{68821e1f-0547-4460-b6db-235e3d4ffaef}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION F_LIN2 : REAL
VAR_INPUT
	X : REAL;
	X1: REAL;
	Y1 : REAL;
	X2 : REAL;
	Y2 : REAL;
END_VAR


(*
version 1.0	1 jan 2007
programmer 	hugo
tested by		tobias

this function calculates the linear equation f_lin = a*x + b given by two points x1/y1 and x2/y2.

*)]]></Declaration>
    <Implementation>
      <ST><![CDATA[F_LIN2 := (Y2 - Y1) / (X2 - X1) * (X - X1) + Y1;


(* revision history
hm	1. jan. 2007	rev 1.0
	original release

hm	17. dec. 2008	rev 1.1
	optimized formula

*)]]></ST>
    </Implementation>
    <LineIds Name="F_LIN2">
      <LineId Id="18" Count="10" />
    </LineIds>
  </POU>
</TcPlcObject>