<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.7">
  <POU Name="F_QUAD" Id="{3c1d3c47-3bbe-40d8-81ac-07bf0d202aea}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION F_QUAD : REAL
VAR_INPUT
	X : REAL;
	A : REAL;
	B : REAL;
	C : REAL;
END_VAR


(*
version 1.1	18. Mar. 2011
programmer 	hugo
tested by		tobias

this function calculates the quadratic equation f_lin = a*x + b

*)]]></Declaration>
    <Implementation>
      <ST><![CDATA[F_QUAD :=  (A * X + B) * X + C;

(* revision history

hm	1. sep. 2006	rev 1.0
	original version

hm	18. mar. 2001	rev 1.1
	improved performance
*)]]></ST>
    </Implementation>
    <LineIds Name="F_QUAD">
      <LineId Id="17" Count="9" />
    </LineIds>
  </POU>
</TcPlcObject>