<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.7">
  <POU Name="CAUCHY" Id="{7ad55883-80f8-489f-9706-47274251ce6e}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION CAUCHY : REAL
VAR_INPUT
	X : REAL;
	T : REAL;
	U : REAL;
END_VAR
VAR
	tmp: REAL;
END_VAR


(*
version 1.0	26. oct. 2008
programmer 	hugo
tested by		tobias

this function calculates the Cauchy distribution function

*)]]></Declaration>
    <Implementation>
      <ST><![CDATA[tmp := x - t;
CAUCHY := math.PI_INV * U / (U*U + tmp*tmp);



(* revision hisdtory
hm	26. oct. 2008	rev 1.0
	original version

*)]]></ST>
    </Implementation>
    <LineIds Name="CAUCHY">
      <LineId Id="19" Count="9" />
    </LineIds>
  </POU>
</TcPlcObject>