<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.7">
  <POU Name="ERFC" Id="{d16983be-2e46-4790-9707-f8f05f7233f3}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION ERFC : REAL
VAR_INPUT
	X : REAL;
END_VAR


(*
version 1.1	10. mar. 2009
programmer 	hugo
tested by		tobias

this function calculates the inverse erf (error) function.

*)]]></Declaration>
    <Implementation>
      <ST><![CDATA[ERFC := 1.0 - ERF(X);

(* revision history
hm	7. apr. 2008	rev 1.0
	original version

hm	10. mar. 2009	rev 1.1
	real constants updated to new systax using dot

*)]]></ST>
    </Implementation>
    <LineIds Name="ERFC">
      <LineId Id="14" Count="9" />
    </LineIds>
  </POU>
</TcPlcObject>