<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.7">
  <POU Name="GAUSSCD" Id="{6aa9491a-6907-4834-a9ac-b28dda15962d}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION GAUSSCD : REAL
VAR_INPUT
	X : REAL;
	U : REAL;
	SI: REAL;
END_VAR


(*
version 1.1	10. mar. 2009
programmer 	hugo
tested by		tobias

this function calculates the gaussian cumulative distribution function

*)]]></Declaration>
    <Implementation>
      <ST><![CDATA[GAUSSCD := (ERF((X - U) / (SI * 1.414213562)) + 1.0) * 0.5;



(* revision hisdtory
hm	6. apr. 2008	rev 1.0
	original version

hm	10. mar. 2009	rev 1.1
	real constants updated to new systax using dot

*)]]></ST>
    </Implementation>
    <LineIds Name="GAUSSCD">
      <LineId Id="16" Count="11" />
    </LineIds>
  </POU>
</TcPlcObject>