<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.7">
  <POU Name="MAX3" Id="{e56e8498-860a-4ec7-be2f-fed18bf916a0}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION MAX3 : REAL
VAR_INPUT
	in1 : REAL;
	in2 : REAL;
	in3 : REAL;
END_VAR


(*
version 1.1	18. mar. 2011
programmer 	hugo
tested by		tobias

this function returns the highest of 3 real values

*)]]></Declaration>
    <Implementation>
      <ST><![CDATA[MAX3 := MAX(MAX(IN1,IN2),IN3);


(* revision history
hm	1.1.2007	rev 1.0
	original release

hm	18. mar. 2011	rev 1.1
	improve performance

*)]]></ST>
    </Implementation>
    <LineIds Name="MAX3">
      <LineId Id="16" Count="10" />
    </LineIds>
  </POU>
</TcPlcObject>