<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.7">
  <POU Name="MUL_ADD" Id="{afd6d914-7b75-48aa-969c-5c093309963d}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION MUL_ADD : REAL
VAR_INPUT
	X : REAL;
	K : REAL;
	O : REAL;
END_VAR


(*
version 1.1	11 nov 2007
programmer 	hugo
tested by		tobias

this function multiplies an input X with K and adds Offset O to the result.

*)]]></Declaration>
    <Implementation>
      <ST><![CDATA[MUL_ADD := X * K + O;

(* revision history
hm	28. feb 2007
	original version

hm	11.nov 2007		rev 1.1
	deleted preset values for K and O this makes no sense for a function

*)]]></ST>
    </Implementation>
    <LineIds Name="MUL_ADD">
      <LineId Id="16" Count="9" />
    </LineIds>
  </POU>
</TcPlcObject>