<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.7">
  <POU Name="F_TO_C" Id="{9b60415b-58ea-4037-a42a-acd7959747e1}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION F_TO_C : REAL
VAR_INPUT
	fahrenheit : REAL;
END_VAR


(*
version 1.1	11. mar. 2009
programmer 	hugo
tested BY		tobias

this FUNCTION converts fahrenheit TO celsius

*)]]></Declaration>
    <Implementation>
      <ST><![CDATA[F_TO_C := (fahrenheit - 32.0) * 0.5555555555555;

(* revision history
hm	4. aug 2006	rev 1.0
	original version

hm	11. mar. 2009	rev 1.1
	real constants updated to new systax using dot

*)]]></ST>
    </Implementation>
    <LineIds Name="F_TO_C">
      <LineId Id="14" Count="9" />
    </LineIds>
  </POU>
</TcPlcObject>