<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.7">
  <POU Name="MS_TO_KMH" Id="{0588b815-07b5-497f-8864-2b44864ea481}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION MS_TO_KMH : REAL
VAR_INPUT
	ms : REAL;
END_VAR


(*
version 1.0	4 Feb 2007
programmer 	hugo
tested by		tobias

this function converts velocities from Meters / Second to Kilometers / hour.

*)]]></Declaration>
    <Implementation>
      <ST><![CDATA[MS_TO_KMH := ms * 3.6;

]]></ST>
    </Implementation>
    <LineIds Name="MS_TO_KMH">
      <LineId Id="14" Count="2" />
    </LineIds>
  </POU>
</TcPlcObject>