<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.7">
  <POU Name="OM_TO_F" Id="{ce71a8a7-2aef-425c-8a14-7eea08398ce8}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION OM_TO_F : REAL
VAR_INPUT
	OM : REAL;
END_VAR


(*
version 1.1	18. oct. 2008
programmer 	hugo
tested by		tobias

this function converts Omega F to frequency
F = OM / (2*PI)
*)]]></Declaration>
    <Implementation>
      <ST><![CDATA[OM_TO_F := OM / math.PI2;


(* revision history
hm	22. jan. 2007	rev 1.0
	original version

hm	18. oct. 2008	rev 1.1
	using math constants

*)]]></ST>
    </Implementation>
    <LineIds Name="OM_TO_F">
      <LineId Id="14" Count="10" />
    </LineIds>
  </POU>
</TcPlcObject>