<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.7">
  <POU Name="PT_TO_F" Id="{2997b14f-676c-4b82-b1d2-8941f2fdf604}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION PT_TO_F : REAL
VAR_INPUT
	PT : TIME;
END_VAR


(*
version 1.1	11. mar. 2009
programmer 	hugo
tested by		tobias

this function converts periode time to frequency
*)]]></Declaration>
    <Implementation>
      <ST><![CDATA[PT_TO_F := 1000.0 / DWORD_TO_REAL(TIME_TO_DWORD(PT));


(*	revision history
hm	4. aug. 2006	rev 1.0
	original version

hm	11. mar. 2009	rev 1.1
	real constants updated to new systax using dot

*)
]]></ST>
    </Implementation>
    <LineIds Name="PT_TO_F">
      <LineId Id="13" Count="11" />
    </LineIds>
  </POU>
</TcPlcObject>