<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.6">
  <POU Name="BaseComponent" Id="{5253bd62-43a4-4dc5-9a8b-6d09f9b444a3}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK BaseComponent
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
	// Time
	ComponentTime: FB_Get_Unix_Timestamp;
	timestamp: ULINT;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="Run" Id="{98d864d5-0f16-4162-8981-2d6b46d665dc}">
      <Declaration><![CDATA[METHOD Run : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="BaseComponent">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="BaseComponent.Run">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>