<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4018.2">
  <POU Name="F_ConvLinAnaOutp" Id="{2f6e3140-07f7-4364-a0af-0019b2692e6f}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION F_ConvLinAnaOutp : ST_OutputVar
VAR_INPUT
	stOutput	:	ST_OutputVar;
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[//nVarOutput = (fVar-fParaC)/fParaM)
stOutput.nVarOutput	:=	REAL_TO_INT((stOutput.fVal - stOutput.fParaC)*stOutput.fParaMaxOutp/stOutput.nParaMaxInt);

//assign output
F_ConvLinAnaOutp	:=	stOutput;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>