<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.7">
  <POU Name="CARG" Id="{6a924c3c-d7ef-48cc-b786-e7eb257a799b}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION CARG : REAL
VAR_INPUT
	X : complex;
END_VAR


(*
version 1.1	20. apr. 2008
programmer 	hugo
tested by	oscat

this function calculates the phase angle (argument) of a complex number

*)]]></Declaration>
    <Implementation>
      <ST><![CDATA[CARG := ATAN2(X.im, X.re);



(* revision history
hm	21. feb. 2008	rev 1.0
	original version

hm	20. apr. 2008	rev 1.1
	use ATAN2 instead of ATAN
*)]]></ST>
    </Implementation>
    <LineIds Name="CARG">
      <LineId Id="14" Count="10" />
    </LineIds>
  </POU>
</TcPlcObject>