<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.7">
  <POU Name="MULTIME" Id="{52b0ec30-d6cd-424e-a3b2-d8823db87b7b}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION MULTIME : TIME
VAR_INPUT
	t : TIME;
	M : REAL;
END_VAR


(*
version 1.1	14 mar 2008
programmer 	hugo
tested by		tobias

multiplies a time by a real number and returns a time
*)]]></Declaration>
    <Implementation>
      <ST><![CDATA[MULTIME := DWORD_TO_TIME(REAL_TO_DWORD(DWORD_TO_REAL(TIME_TO_DWORD(t))*M));

(* revision history
hm		2. oct 2006	rev 1.0
	original version

hm		14. mar 2008	rev 1.1
	rounded the result after the last digit

*)]]></ST>
    </Implementation>
    <LineIds Name="MULTIME">
      <LineId Id="14" Count="9" />
    </LineIds>
  </POU>
</TcPlcObject>