<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.7">
  <POU Name="YEAR_OF_DATE" Id="{a6e658a7-be6d-4346-9c82-269bf7a39688}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION YEAR_OF_DATE : INT
VAR_INPUT
	IDATE : DATE;
END_VAR


(*
version 1.4	7. oct. 2008
programmer 	hugo
tested by		oscat

returs the year of a date  
the function works for dates from 1970 - 2099 

*)
]]></Declaration>
    <Implementation>
      <ST><![CDATA[YEAR_OF_DATE := DWORD_TO_INT((DATE_TO_DWORD(idate) + 43200) / 31557600 + 1970);


(* revision history
hm	4. aug 2006		rev 1.0
	original version

hm	1. okt 2007		rev 1.1
	corrected error in algorithm
	adjustment for S7 compatibility

hm	23.12.2007		rev 1.2
	changed code for better performance

hm	7. apr. 2008	rev 1.3
	deleted unused step7 code

hm	7. oct. 2008	rev 1.4
	renamed function (year) to year_of_date

*)]]></ST>
    </Implementation>
    <LineIds Name="YEAR_OF_DATE">
      <LineId Id="16" Count="20" />
    </LineIds>
  </POU>
</TcPlcObject>