<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.7">
  <POU Name="CSIN" Id="{a280ced1-3b06-43fc-b992-64619d8d8a51}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION CSIN : complex
VAR_INPUT
	X : complex;
END_VAR


(*
version 1.0	21 feb 2008
programmer 	hugo
tested by	oscat

this function calculates the sinus function of a complex number

*)]]></Declaration>
    <Implementation>
      <ST><![CDATA[CSIN.re := cosH(X.im) * SIN(X.re);
CSIN.im := sinH(X.im) * COS(X.re);


(* revision history
hm	21. feb 2008	rev 1.0
	original version

*)]]></ST>
    </Implementation>
    <LineIds Name="CSIN">
      <LineId Id="14" Count="8" />
    </LineIds>
  </POU>
</TcPlcObject>