<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.7">
  <POU Name="CSUB" Id="{478648e2-2b49-4da3-a830-1d97699d9850}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION CSUB : complex
VAR_INPUT
	X, Y : complex;
END_VAR


(*
version 1.0	21 feb 2008
programmer 	hugo
tested by	oscat

this function subtracts two complex numbers

*)]]></Declaration>
    <Implementation>
      <ST><![CDATA[CSUB.re := X.re - Y.re;
CSUB.im := X.im - Y.im;

(* revision history
hm	21. feb 2008	rev 1.0
	original version

*)]]></ST>
    </Implementation>
    <LineIds Name="CSUB">
      <LineId Id="14" Count="7" />
    </LineIds>
  </POU>
</TcPlcObject>