<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.7">
  <POU Name="V3_DPRO" Id="{53179251-4777-49fe-94b5-3a17098b2b6e}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION V3_DPRO : REAL
VAR_INPUT
	A : Vector_3;
	B : Vector_3;
END_VAR


(*
version 1.0	11 dec 2007
programmer 	hugo
tested by		tobias

this function calculates the dot product of two vectors in 3 dimensional space

*)]]></Declaration>
    <Implementation>
      <ST><![CDATA[V3_DPRO := A.X * B.X + A.Y * B.Y + A.Z * B.Z;


(* revision history
hm		11 dec 2007	rev 1.0
	original version

*)]]></ST>
    </Implementation>
    <LineIds Name="V3_DPRO">
      <LineId Id="15" Count="7" />
    </LineIds>
  </POU>
</TcPlcObject>