<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.7">
  <POU Name="V3_NUL" Id="{7eb1dc81-ee66-4857-aa2a-a45eb5a32a1f}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION V3_NUL : BOOL
VAR_INPUT
	A : Vector_3;
END_VAR


(*
version 1.1	10. mar. 2009
programmer 	hugo
tested by		tobias

this function checks if a vectors in a null Vector

*)]]></Declaration>
    <Implementation>
      <ST><![CDATA[V3_NUL := A.X = 0.0 AND A.Y = 0.0 AND A.Z = 0.0;



(* revision history
hm	12 dec 2007	rev 1.0
	original version

hm	10. mar. 2009	rev 1.1
	changed syntax of real constants to 0.0

*)]]></ST>
    </Implementation>
    <LineIds Name="V3_NUL">
      <LineId Id="14" Count="11" />
    </LineIds>
  </POU>
</TcPlcObject>