<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.7">
  <POU Name="AGDF" Id="{6c73f20b-c5b3-41fd-9a36-a2124627b1e8}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION AGDF : REAL
VAR_INPUT
	X : REAL;
END_VAR


(*
version 1.1	10. mar. 2009
programmer 	hugo
tested by		tobias

this function calculates the inverse Gudermannian function.

*)]]></Declaration>
    <Implementation>
      <ST><![CDATA[AGDF := LN((1.0 + SIN(X)) / COS(X));

(* comment
the current implementation gives sufficient accuracy only up to X = 1.57 or an output > 10.
is X closer to PI/2 then the function is more and more unreliable
*)



(* revision history
hm	27. apr. 2008	rev 1.0
	original version

hm	10. mar. 2009	rev 1.1
	real constants updated to new systax using dot

*)
]]></ST>
    </Implementation>
    <LineIds Name="AGDF">
      <LineId Id="14" Count="17" />
    </LineIds>
  </POU>
</TcPlcObject>