<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.7">
  <POU Name="ASINH" Id="{4e4a4ad6-dd27-43f5-a5de-34f2af3b694a}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION ASINH : REAL
VAR_INPUT
	X : REAL;
END_VAR


(*
version 1.3	10. mar 2009
programmer 	hugo
tested by		tobias

this function calculates the arcus sin hyperbolicus

*)]]></Declaration>
    <Implementation>
      <ST><![CDATA[ASINH := LN(SQRT(X * X + 1.0)+X);

(* revision history
hm		12 jan 2007	rev 1.0
	original version

hm		2. dec 2007	rev 1.1
	changed code for better performance

hm		16.3. 2007		rev 1.2
	changed sequence of calculations to improve performance

hm	10. mar. 2009		rev 1.3
	real constants updated to new systax using dot

*)]]></ST>
    </Implementation>
    <LineIds Name="ASINH">
      <LineId Id="14" Count="15" />
    </LineIds>
  </POU>
</TcPlcObject>