<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.7">
  <POU Name="DIFFER" Id="{2925ae31-d7b5-44d2-acfe-4c4c96f7b22d}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION DIFFER : BOOL
VAR_INPUT
	in1 : REAL;
	in2 : REAL;
	X : REAL;
END_VAR


(*
version 1.1	16 mar 2008
programmer 	hugo
tested by		tobias

this function checks if in1 differs more then x from in2
the output is true if abs(in1-in2) > X

*)]]></Declaration>
    <Implementation>
      <ST><![CDATA[DIFFER := ABS(in1 - in2) > X;

(* revision history
hm		8. oct 2006		rev 1.0
	original version

hm		16. mar 2008	rev 1.1
	improverd code for performance

*)]]></ST>
    </Implementation>
    <LineIds Name="DIFFER">
      <LineId Id="17" Count="9" />
    </LineIds>
  </POU>
</TcPlcObject>