<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.7">
  <POU Name="INC2" Id="{f5c0cba9-7362-4ebc-877d-127f2c40dd57}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION INC2 : INT
VAR_INPUT
	X : INT;
	D : INT;
	L : INT;
	U : INT;
END_VAR
VAR
	tmp: INT;
END_VAR


(*
version 1.0	29. jun. 2008
programmer 	hugo
tested by	oscat

This function increments the input X by the value D and compares the result with U.
if the output exceeds U it will continue to count from L again.

*)]]></Declaration>
    <Implementation>
      <ST><![CDATA[tmp := U - L + 1;
INC2 := (X + D - L + tmp) MOD tmp + L;



(* revision history
hm	29. jun. 2008		REV 1.0
	original version


*)]]></ST>
    </Implementation>
    <LineIds Name="INC2">
      <LineId Id="21" Count="10" />
    </LineIds>
  </POU>
</TcPlcObject>