<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.7">
  <POU Name="MIN3" Id="{9dc4f673-5ee9-4c0a-ad2c-b798009749b5}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION MIN3 : REAL
VAR_INPUT
	in1 : REAL;
	in2 : REAL;
	in3 : REAL;
END_VAR


(*
version 1.1	18. mar. 2011
programmer 	hugo
tested by		tobias

this function returns the lowest of 3 real values

*)]]></Declaration>
    <Implementation>
      <ST><![CDATA[MIN3 := MIN(MIN(IN1,IN2),IN3);


(* revision history
hm	1.1.2007	rev 1.0
	original release

hm	18. mar. 2011	rev 1.1
	improve performance

*)]]></ST>
    </Implementation>
    <LineIds Name="MIN3">
      <LineId Id="16" Count="10" />
    </LineIds>
  </POU>
</TcPlcObject>