<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.7">
  <POU Name="WINDOW" Id="{2fea4a06-ab47-49ab-ae1b-c8acfe14550f}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION WINDOW : BOOL
VAR_INPUT
	low : REAL;
	in : REAL;
	high : REAL;
END_VAR


(*
	version 1.1	22 jan 2007
	programmer 	hugo
	tested BY	tobias

this checks a signal if the signal is between the upper and lower limit
*)]]></Declaration>
    <Implementation>
      <ST><![CDATA[WINDOW := in < high AND in > low;


(* revision history
hm	22.1.2007	rev 1.1
	changed the order of inputs to low, in, high

*)]]></ST>
    </Implementation>
    <LineIds Name="WINDOW">
      <LineId Id="15" Count="7" />
    </LineIds>
  </POU>
</TcPlcObject>