<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.7">
  <POU Name="HOUR" Id="{d11fc8e8-349a-44ab-a706-c797a1389958}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION HOUR : INT
VAR_INPUT
	itod : TOD;
END_VAR


(*
version 1.1	2 okt 2006
programmer 	hugo
tested by	tobias

extracts the hour of a Time_of_day 
*)]]></Declaration>
    <Implementation>
      <ST><![CDATA[HOUR := DWORD_TO_INT(TOD_TO_DWORD(itod) / 3600000);


(* change history
hm 4. aug 2006	rev 1.0
	original version

hm 2.10.2006 	rev 1.1
	changed name of input to itod

*)]]></ST>
    </Implementation>
    <LineIds Name="HOUR">
      <LineId Id="13" Count="10" />
    </LineIds>
  </POU>
</TcPlcObject>