<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.7">
  <POU Name="HOUR_OF_DT" Id="{cc89b416-0757-4c44-8c52-7267686853a1}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION HOUR_OF_DT : INT
VAR_INPUT
	XDT : DT;
END_VAR


(*
	version 1.0	6. jun. 2008
	programmer 	oscat
	tested BY	oscat

HOUR_OF_DT returns the current hour (hour of the day) of a DT variable

*)]]></Declaration>
    <Implementation>
      <ST><![CDATA[HOUR_OF_DT := DWORD_TO_INT((DT_TO_DWORD(XDT) MOD 86400) / 3600);


(* revision history
hm		6.9.2008	rev 1.0
	original version


*)]]></ST>
    </Implementation>
    <LineIds Name="HOUR_OF_DT">
      <LineId Id="14" Count="8" />
    </LineIds>
  </POU>
</TcPlcObject>