<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.7">
  <POU Name="MONTH_END" Id="{5bb8cfc9-37ed-4ffd-bbe2-ca8d2e72557b}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION MONTH_END : DATE
VAR_INPUT
	IDATE : DATE;
END_VAR


(*
version 1.1	7. oct. 2008
programmer 	hugo
tested by	oscat

returns the date for the last day of the current month in the current year.

*)]]></Declaration>
    <Implementation>
      <ST><![CDATA[MONTH_END := DWORD_TO_DATE(DATE_TO_DWORD(SET_DATE(YEAR_OF_DATE(idate),MONTH_OF_DATE(idate)+1,1)) - 86400);



(* revision history
hm	15. jun. 2008	rev 1.0
	original version	

hm	7. oct. 2008	rev 1.1
	changed function year to year_of_date
	changed function month to month_of_date

*)]]></ST>
    </Implementation>
    <LineIds Name="MONTH_END">
      <LineId Id="14" Count="12" />
    </LineIds>
  </POU>
</TcPlcObject>