<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.7">
  <POU Name="SDT_TO_TOD" Id="{c9b56493-462a-4c5d-9619-abeb66bf9f75}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION SDT_TO_TOD : TOD
VAR_INPUT
	DTI : SDT;
END_VAR


(*
version 1.1	16. nov. 2008
programmer 	hugo
tested by	oscat

converts Structured date time (SDT) to Date Time

*)
]]></Declaration>
    <Implementation>
      <ST><![CDATA[SDT_TO_TOD := DWORD_TO_TOD(INT_TO_DWORD(DTI.HOUR) * 3600000 + INT_TO_DWORD(DTI.MINUTE) * 60000 + INT_TO_DWORD(DTI.SECOND) * 1000 + INT_TO_DWORD(DTI.MS));



(* revision history

hm 18. oct. 2008	rev 1.0
	original version

hm	16. nov. 2008	rev 1.1
	added typecasts to avoid warnings
*)]]></ST>
    </Implementation>
    <LineIds Name="SDT_TO_TOD">
      <LineId Id="15" Count="11" />
    </LineIds>
  </POU>
</TcPlcObject>