<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.7">
  <POU Name="SDT_TO_DATE" Id="{fabd3a0c-1273-4d08-91a3-a79770d1a8e0}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION SDT_TO_DATE : DATE
VAR_INPUT
	DTI : SDT;
END_VAR


(*
version 1.0	18. oct 2008
programmer 	hugo
tested by	oscat

converts Structured date time (SDT) to Date Time

*)
]]></Declaration>
    <Implementation>
      <ST><![CDATA[SDT_TO_DATE := SET_DATE(DTI.YEAR, DTI.MONTH, DTI.DAY);



(* revision history

hm 18. oct. 2008	rev 1.0
	original version

*)]]></ST>
    </Implementation>
    <LineIds Name="SDT_TO_DATE">
      <LineId Id="15" Count="9" />
    </LineIds>
  </POU>
</TcPlcObject>