<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.7">
  <POU Name="SECOND" Id="{ae2ad288-c298-4d7c-9c8d-7d7654dba13d}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION SECOND : REAL
VAR_INPUT
	itod : TOD;
END_VAR


(*
version 1.1	2 oct 2006
programmer 	hugo
tested by	oscat

returns the seconds and milliseconds as real of TOD   
 
*)]]></Declaration>
    <Implementation>
      <ST><![CDATA[SECOND := DWORD_TO_REAL(TOD_TO_DWORD(itod) - TOD_TO_DWORD(itod)/60000 * 60000) / 1000.0;



(* change history

hm	2. oct. 2006 rev 1.1 
	changed name of input to itod

*)]]></ST>
    </Implementation>
    <LineIds Name="SECOND">
      <LineId Id="14" Count="9" />
    </LineIds>
  </POU>
</TcPlcObject>