<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.7">
  <POU Name="V3_ABS" Id="{aca9afaa-d5e6-4a5c-959b-6eebc8d2ea7e}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION V3_ABS : REAL
VAR_INPUT
	A : Vector_3;
END_VAR


(*
version 1.0	11 dec 2007
programmer 	hugo
tested by		tobias

this function calculates the length of a vectors in a 3 dimensional space

*)]]></Declaration>
    <Implementation>
      <ST><![CDATA[V3_ABS := SQRT(A.X * A.X + A.Y * A.Y + A.Z * A.Z);


(* revision history
hm		11 dec 2007	rev 1.0
	original version

*)]]></ST>
    </Implementation>
    <LineIds Name="V3_ABS">
      <LineId Id="14" Count="7" />
    </LineIds>
  </POU>
</TcPlcObject>