<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.7">
  <POU Name="REVERSE" Id="{bffd8a9a-3ea0-4be3-acee-022aa8f946a2}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION REVERSE : BYTE
VAR_INPUT
	IN : BYTE;
END_VAR


(*
	version 1.1	18. feb 2008
	programmer 	hugo
	tested BY		tobias

This function reverses the bits of a byte so that after execution bit 7 is at bit 0 location and so forth.

*)]]></Declaration>
    <Implementation>
      <ST><![CDATA[REVERSE := SHL(in,7) OR SHR(in,7) OR (ROR(in,3) AND 2#01000100) OR (ROL(in,3) AND 2#00100010)
	OR (SHL(in,1) AND 2#00010000) OR (SHR(in,1) AND 2#00001000);


(* revision history
hm		9.oct 2007		rev 1.0
	original version

hm		18. feb 2008	rev 1.1
	improved performance
*)]]></ST>
    </Implementation>
    <LineIds Name="REVERSE">
      <LineId Id="14" Count="10" />
    </LineIds>
  </POU>
</TcPlcObject>