<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.7">
  <POU Name="F_TO_PT" Id="{396fea13-c652-4b6e-aa00-1e474fc81b35}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION F_TO_PT : TIME
VAR_INPUT
	F : REAL;
END_VAR


(*
version 1.1	11. mar. 2009
programmer 	hugo
tested by		tobias

this function converts frequency to periode time  
*)]]></Declaration>
    <Implementation>
      <ST><![CDATA[F_TO_PT := DWORD_TO_TIME(REAL_TO_DWORD(1.0 / F * 1000.0));


(* revision history

hm	4. aug. 2006	rev 1.0
	original version

hm	11. mar. 2009	rev 1.1
	real constants updated to new systax using dot

*)
]]></ST>
    </Implementation>
    <LineIds Name="F_TO_PT">
      <LineId Id="13" Count="12" />
    </LineIds>
  </POU>
</TcPlcObject>