<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.7">
  <POU Name="CCOSH" Id="{8128f1a1-40e3-430d-8c8b-290db95b040d}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION CCOSH : complex
VAR_INPUT
	X : complex;
END_VAR


(*
version 1.0	21 feb 2008
programmer 	hugo
tested by	oscat

this function calculates the arcus tangens function of a complex number

*)]]></Declaration>
    <Implementation>
      <ST><![CDATA[CCOSH.re := cosH(x.re) * COS(x.im);
CCOSH.im := sinH(x.re) * SIN(x.im);


(* revision history
hm	21. feb 2008	rev 1.0
	original version

*)]]></ST>
    </Implementation>
    <LineIds Name="CCOSH">
      <LineId Id="14" Count="8" />
    </LineIds>
  </POU>
</TcPlcObject>