<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.7">
  <POU Name="R2_ADD2" Id="{d0fb6726-bb1e-44b1-990f-28951c8eb505}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION R2_ADD2 : REAL2
VAR_INPUT
	X : Real2;
	Y : REAL2;
END_VAR


(*
version 1.0	20. mar. 2008
programmer 	hugo
tested by		tobias

R2_add2 adds a double precision real to a double precision real which extends the accuracy of a real to twice as many digits

*)]]></Declaration>
    <Implementation>
      <ST><![CDATA[R2_ADD2.R1 := X.R1 + Y.R1;
R2_ADD2.RX := X.RX + Y.RX;


(* revision history
hm		20.3.2008	rev 1.0
	original version

*)]]></ST>
    </Implementation>
    <LineIds Name="R2_ADD2">
      <LineId Id="15" Count="8" />
    </LineIds>
  </POU>
</TcPlcObject>