<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.7">
  <POU Name="CIRCLE_C" Id="{2e62ee36-26f5-4c74-841b-963b4f99870d}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION CIRCLE_C : REAL
VAR_INPUT
	Rx : REAL;
	Ax : REAL;
END_VAR


(*
version 1.1	22 feb 2008
programmer 	hugo
tested by		tobias

circle_C calculates the Circumference of a circle  if ax = 360 the whole circle is calculated

*)
]]></Declaration>
    <Implementation>
      <ST><![CDATA[circle_C := 1.7453293E-2 * Rx * Ax;

(* revision histroy
hm	16. oct 2007	rev 1.0
	original version

hm	22. feb 2008	rev 1.1
	improved performance
*)]]></ST>
    </Implementation>
    <LineIds Name="CIRCLE_C">
      <LineId Id="16" Count="8" />
    </LineIds>
  </POU>
</TcPlcObject>