<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.7">
  <POU Name="ELLIPSE_A" Id="{bf6fdb9c-cc1b-4dce-8b87-83715b509ec9}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION ELLIPSE_A : REAL
VAR_INPUT
	R1 : REAL;
	R2 : REAL;
END_VAR


(*
version 1.1	18. oct. 2008
programmer 	hugo
tested by	oscat

ellipse_A calculates the Area of an ellipe based on the two radians R1 and R2


*)
]]></Declaration>
    <Implementation>
      <ST><![CDATA[ELLIPSE_A := math.PI * R1 * R2;

(* revision histroy
hm	16. oct 2007	rev 1.0
	original version

hm	18. oct. 2008	rev 1.1
	using math constants
*)]]></ST>
    </Implementation>
    <LineIds Name="ELLIPSE_A">
      <LineId Id="17" Count="8" />
    </LineIds>
  </POU>
</TcPlcObject>